name: NameRetriever
main: com.andoutay.nameretriever.NameRetriever
version: 1.1.1

description: >
             NameRetriever provides a simple way to get the nickname or minecraft name of a player whether online or off based on the other by interfacing with Essentials

softdepend: [Essentials]

commands:
    realname:
        description: Gets the Minecraft name of a player based on their display name
        usage: 'usage: /<command> <nickname>'
        aliases: [name, rname]
    realnick:
        description: Gets the nickname of a player based on their Minecraft name
        usage: 'usage: /<command> <username>'
        aliases: rnick
    nameretriever:
        description: Reloads config or lists the version of NameRetriever. Also used to get help for the plugin
        usage: 'usage: /<command> <reload|version|help>'
        aliases: nr

permissions:
    nameretriever.*:
        description: Gives access to all NameRetriever commands
        default: false
        children:
            nameretriever.realname: true
            nameretriever.realnick: true
            nameretriever.reload: true
            nameretriever.version: true
            nameretriever.help: true
    nameretriever.realname:
        description: Gives access to the /realname command
        default: false
    nameretriever.realnick:
        description: Gives access to the /realnick command
        default: false
    nameretriever.reload:
        description: Gives access to /nameretriever reload
        default: false
    nameretriever.version:
        description: Gives access to /nameretriever version
        default: false
    nameretriever.help:
        description: Gives access to /nameretriever help
        default: false